# ===============================
# APP
# ===============================
spring.application.name=htms
spring.config.import=optional:file:htms/.env[.properties]
server.port=${SERVER_PORT:8080}
# ===============================
# DATABASE - PostgreSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
# ===============================
# JWT
# ===============================
JWT_ACCESSKEY=${JWT_ACCESSKEY}
JWT_REFRESHKEY=${JWT_REFRESHKEY}
JWT_ACCESSEXPIRATION=${JWT_ACCESSEXPIRATION}
JWT_REFRESHEXPIRATION=${JWT_REFRESHEXPIRATION}

